main:
	
	gcc -c -o ./lib/hellofunc.o ./src/hellofunc.c -I./include
	gcc -c -o ./lib/helloMake.o ./src/helloMake.c -I./include
	gcc -o ./build/hello ./lib/hellofunc.o ./lib/helloMake.o -I./include
	hello